name: Dispatch to Main Repo

on:
  push:
    branches:
      - master

jobs:
  dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger main repo workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: octo-kumo/octo-kumo.github.io
          event-type: submodule-updated
